version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_qap
    environment:
      MYSQL_DATABASE: hockey_db_2024
      MYSQL_ROOT_PASSWORD: Keyin202!
      MYSQL_PASSWORD: Keyin202!
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
