#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2vcezehro2.us-east-1.rds.amazonaws.com/fall_2022
spring.datasource.url=jdbc:mysql://localhost:3306/s4_2024_hockey_reg_system_api
spring.datasource.username=root
spring.datasource.password=Keyin202!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration


